version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../mariadb/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "root"
    networks:
      - backend

  nodejs_app1:
    image: test_nodejs_app1:latest
    networks:
      - backend
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "8087:8080"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/certs:/etc/nginx/certs
    networks:
      - frontend
      - backend

  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3001:3000"  # Utilise le port 3001 pour éviter les conflits
    networks:
      - backend
      
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      --nginx.scrape-uri=http://localhost:8087/stub_status
    expose: 
      - 9113
    networks:
      - backend
    depends_on:
      - prometheus


volumes:
  mariadb_data:
  prometheus_data:
  grafana_data:

networks:
  frontend:
  backend:
