version: '3.7'

services:
  mariadb-master:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "root"
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: replica
      MYSQL_REPLICATION_PASSWORD: replica_pass
    volumes:
      - mariadb_data_master:/var/lib/mysql
      - ../mariadb/master/my.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ../mariadb/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend
    deploy:
      replicas: 1
    hostname: mariadb-master
  mariadb-slave:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "root"
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: "replica"
      MYSQL_REPLICATION_PASSWORD: "replica_pass"
      MYSQL_MASTER_HOST: mariadb-master
      MYSQL_MASTER_PORT: 3306
    volumes:
      - mariadb_data_slave:/var/lib/mysql
      - ../mariadb/slave/my.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ../mariadb/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend
    deploy:
      replicas: 1
    hostname: mariadb-slave

  nodejs_app1:
    image: test_nodejs_app1:latest
    networks:
      - backend
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "8087:8080"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/certs:/etc/nginx/certs
    networks:
      - frontend
      - backend

  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3001:3000"  # Utilise le port 3001 pour éviter les conflits
    networks:
      - backend
      
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      --nginx.scrape-uri=http://localhost:8087/stub_status
    expose: 
      - 9113
    networks:
      - backend
    depends_on:
      - prometheus

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb-master  # Le nom du service MariaDB
      PMA_USER: "appuser"  # Utilisateur MariaDB
      PMA_PASSWORD: "root"  # Mot de passe de l'utilisateur MariaDB

    networks:
      - backend
    depends_on:
      - mariadb

volumes:
  mariadb_data_master:
  mariadb_data_slave:
  prometheus_data:
  grafana_data:

networks:
  frontend:
  backend:


